name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: Build using NPM
        run: npm run build

      - name: Setup ID SSH key
        env:
          SSH_KEY_PUBLIC: ${{ secrets.SSH_KEY_PUBLIC }}
          SSH_KEY_PRIVATE: ${{ secrets.SSH_KEY_PRIVATE }}
        run: |
          cd
          mkdir -m 700 .ssh
          cd .ssh
          echo "$SSH_KEY_PUBLIC" > id_rsa.pub
          chmod 644 id_rsa.pub
          echo "$SSH_KEY_PRIVATE" > id_rsa
          chmod 600 id_rsa

      - name: Copy build to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP_ADDRESS: ${{ secrets.SERVER_IP_ADDRESS }}
        run: scp -r build/ "${SERVER_USER}@${SERVER_IP_ADDRESS}:/var/www/www.matbadev.com-$(date +%s)/"
