name: deploy

on:
  push:
    branches:
      - master
  # Allow workflow to be triggered manually.
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install NPM dependencies
        run: npm install

      - name: Build using NPM
        run: npm run build

      - name: Setup SSH
        env:
          SSH_KEY_PUBLIC: ${{ secrets.SSH_KEY_PUBLIC }}
          SSH_KEY_PRIVATE: ${{ secrets.SSH_KEY_PRIVATE }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          cd
          mkdir -m 700 .ssh
          cd .ssh
          echo "$SSH_KEY_PUBLIC" > id_rsa.pub
          chmod 644 id_rsa.pub
          echo "$SSH_KEY_PRIVATE" > id_rsa
          chmod 600 id_rsa
          echo "$SSH_KNOWN_HOSTS" > known_hosts
          chmod 600 known_hosts

      - name: Upload build to server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: scp -P "${SSH_PORT}" -r build/ "${SSH_USER}@${SSH_HOST}:/var/www/www.matbadev.com/${GITHUB_RUN_NUMBER}/"

      - name: Activate uploaded build
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: ssh -p "${SSH_PORT}" -t "${SSH_USER}@${SSH_HOST}" "ln -sfn ${GITHUB_RUN_NUMBER} /var/www/www.matbadev.com/current"
